
name: Deploy to Updatesite

on:
  push:
    branches:
      - main
  pull_request:
jobs: 
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy 🚀
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBACTION_TOKEN_SECRET }}
      run: |
        git clone https://CE7:$GITHUB_TOKEN@github.com/minova-afis/aero.minova.rcp.updatesite # This works
        git config user.email "erlanger@minova.com"
        git config user.name "CE7"
