# This workflow will build the Eclipse RCP application with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RCP build on Win OS and Mac

on:
  push:
    branches:
      - main
  pull_request:
jobs: 
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy 🚀
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo ${{ secrets.GITHUB_TOKEN }}
        echo $GITHUB_TOKEN
        git clone https://$GITHUB_TOKEN@github.com/minova-afis/aero.minova.rcp.updatesite # This works
        git config user janiak-minova 
        git config user.email 
