# This workflow will build the Eclipse RCP application with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RCP build on Win OS and Mac

on:
  push:
    branches:
      - master
      - scr_sonarqube
  pull_request:
  workflow_dispatch:

jobs: 
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        java: [ '11.0.14' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11.0.14
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: |
        mvn clean verify surefire-report:report --fae --file pom.xml --settings .github/settings.xml
      env:
        MAIN_GITHUB_RELEASE_USERNAME: ${{ secrets.MAIN_GITHUB_RELEASE_USERNAME }}
        MAIN_GITHUB_RELEASE_TOKEN: ${{ secrets.MAIN_GITHUB_RELEASE_TOKEN }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: /**/surefire-reports/*.xml
