name: Tag WFC-Application

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release (major.minor.patch)'
        required: true
      description:
        description: 'Beschreibung'
        required: true

jobs:
  tagWFC:
  
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Checkout aero.minova.rcp
      uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # Version in der Pom.xml und allen anderen Paketen inkrementieren und Commiten
    - name: Increment Version 
      run: mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion="${{ github.event.inputs.version }}.qualifier"
    - name: Git commit Version 
      run: |
       git config user.email "erlanger@minova.com"
       git config user.name "CE7"
       git add . 
       git commit -m "Increment Version to ${{ github.event.inputs.version }}, ${{ github.event.inputs.description }}"
       git push
       
    # Version als tag anlegen
    - name: Tag version
      run: |
        git config user.email "erlanger@minova.com"
        git config user.name "CE7"
        git tag -a "v${{ github.event.inputs.version }}" -m "${{ github.event.inputs.description }}"
        git push --tags
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    # Bauen
    - name: Build with Maven 
      run: mvn --batch-mode --update-snapshots verify --file pom.xml
    
    # Zips hochladen
    - name: Copy .zip to Stage area
      run: mkdir staging && cp releng/aero.minova.rcp.product/target/products/*.zip staging
    - name: Upload .zip 
      uses: actions/upload-artifact@v2
      with:
        name: aero.minova.rcp ${{ github.event.inputs.version }}
        path: staging
